### PR TITLE
block stores: prevent the chain head block from being deleted

### PR DESCRIPTION
**Pull request by eu321**

### CODE REVIEW

**Comment by Warchant** [comment]
Why do we store chainHead at all? We must keep both tables in sync, and this is extra effort. 

We can query a row with biggest id (last row) to get chainhead.

**Comment by eu321** [comment]
the chain head points to the best chain, not the last block added, the block with the highest height etc

**Comment by Warchant** [comment]
@eu321 what is the "best chain" here?

**Comment by eu321** [comment]
The meaning is the same as in bitcoin, the chain chosen by a consensus algo.

**Review by Warchant — APPROVED** [review]

**Pull request merged**
