### PR TITLE
StreamUtils: swap parameter order from max/min to min/max

### PR DESCRIPTION
**Pull request by bitspill**
Specifying min first feels more intuitive to me however if there's a convention or standard I'm unaware of specifying max first, so be it

### CODE REVIEW

**Comment by Warchant** [comment]
Very dangerous change, as `min` and `max` have same type, and after you change their order, compiler will not generate any warnings. 

Are you sure you changed position in all places?

**Comment by bitspill** [comment]
This PR can be independently reconstructed via IntelliJ using search+replace in RegEx mode to swap the function definitions and usages at the same time

To first compose a list of functions with max/min parameters a quick search for `max.*min` then for each result the following search -> replace

1) `checkLength\((.*?), (.*?), (.*?)\)` -> `checkLength\($1, $3, $2\)` -- 4 replacements across 1 file
2) `getVariableLengthValue\((.*?), (.*?), (.*?)\)` -> `getVariableLengthValue\($1, $3, $2\)` == 10 replacements across 2 files
3) `getSingleByteLengthValue\((.*?), (.*?), (.*?)\)` -> `getSingleByteLengthValue\($1, $3, $2\)` == 19 replacements across 3 files

In a number of cases the min/max are the same constant so they don't appear in the diff however this should cover all cases


I agree it's not an easy change to make as the compiler can provide no assistance but that's also why I feel it's a beneficial change to get in early -- if however max/min is already established within the teams mindset or methodology it may be difficult to switch already lessening the benefit of this change and future devs will simply have to RTFM

**Review by Warchant — APPROVED** [review]

**Comment by Warchant** [comment]
Will be merged after #3 #4

**Review by blackyblack — APPROVED** [review]
Checked with the linked projects. Looks fine.

**Pull request merged**
